name: Sync Image

on:
  schedule:
    - cron: '0 17 * * *'
  issue_comment:
    types: [created]

jobs:
  image_sync:
    name: Synce image from swr to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Fetch image
        run: |
          sudo docker login -u ap-southeast-3@${{ secrets.SWR_AK }} -p ${{ secrets.SWR_SK }} swr.ap-southeast-3.myhuaweicloud.com

          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/openstack-cloud-controller-manager-amd64:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/cinder-csi-plugin-amd64:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/k8s-keystone-auth-amd64:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/octavia-ingress-controller-amd64:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/manila-csi-plugin-amd64:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/barbican-kms-plugin-amd64:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/magnum-auto-healer-amd64:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/openstack-cloud-controller-manager:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/cinder-csi-plugin:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/k8s-keystone-auth:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/octavia-ingress-controller:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/manila-csi-plugin:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/barbican-kms-plugin:latest
          sudo docker pull swr.ap-southeast-3.myhuaweicloud.com/openlab/magnum-auto-healer:latest

          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/openstack-cloud-controller-manager-amd64:latest k8scloudprovider/openstack-cloud-controller-manager-amd64:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/cinder-csi-plugin-amd64:latest k8scloudprovider/cinder-csi-plugin-amd64:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/k8s-keystone-auth-amd64:latest k8scloudprovider/k8s-keystone-auth-amd64:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/octavia-ingress-controller-amd64:latest k8scloudprovider/octavia-ingress-controller-amd64:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/manila-csi-plugin-amd64:latest k8scloudprovider/manila-csi-plugin-amd64:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/barbican-kms-plugin-amd64:latest k8scloudprovider/barbican-kms-plugin-amd64:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/magnum-auto-healer-amd64:latest k8scloudprovider/magnum-auto-healer-amd64:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/openstack-cloud-controller-manager:latest k8scloudprovider/openstack-cloud-controller-manager:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/cinder-csi-plugin:latest k8scloudprovider/cinder-csi-plugin:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/k8s-keystone-auth:latest k8scloudprovider/k8s-keystone-auth:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/octavia-ingress-controller:latest k8scloudprovider/octavia-ingress-controller:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/manila-csi-plugin:latest k8scloudprovider/manila-csi-plugin:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/barbican-kms-plugin:latest k8scloudprovider/barbican-kms-plugin:latest
          sudo docker tag swr.ap-southeast-3.myhuaweicloud.com/openlab/magnum-auto-healer:latest k8scloudprovider/magnum-auto-healer:latest

          sudo docker logout swr.ap-southeast-3.myhuaweicloud.com
      - name: Sync image
        run: |
          sudo docker login -u ${{ secrets.HUB_NAME }} -p ${{ secrets.HUB_PASSWORD }}

          sudo docker push k8scloudprovider/openstack-cloud-controller-manager-amd64:latest
          sudo docker push k8scloudprovider/cinder-csi-plugin-amd64:latest
          sudo docker push k8scloudprovider/k8s-keystone-auth-amd64:latest
          sudo docker push k8scloudprovider/octavia-ingress-controller-amd64:latest
          sudo docker push k8scloudprovider/manila-csi-plugin-amd64:latest
          sudo docker push k8scloudprovider/barbican-kms-plugin-amd64:latest
          sudo docker push k8scloudprovider/magnum-auto-healer-amd64:latest
          sudo docker push k8scloudprovider/openstack-cloud-controller-manager:latest
          sudo docker push k8scloudprovider/cinder-csi-plugin:latest
          sudo docker push k8scloudprovider/k8s-keystone-auth:latest
          sudo docker push k8scloudprovider/octavia-ingress-controller:latest
          sudo docker push k8scloudprovider/manila-csi-plugin:latest
          sudo docker push k8scloudprovider/barbican-kms-plugin:latest
          sudo docker push k8scloudprovider/magnum-auto-healer:latest

          sudo docker logout
